"""
Voiceover generation using gTTS (simple TTS).

This turns script text into an MP3 file.
"""

from pathlib import Path

from gtts import gTTS


def generate_voiceover(
    script_text: str,
    output_path: Path,
    lang: str = "en",
    slow: bool = False,
) -> Path:
    """
    Generate an MP3 voiceover from script_text.

    :param script_text: The narration text
    :param output_path: Where to save the .mp3
    :param lang: Language code (default: 'en')
    :param slow: If True, speaks a bit slower
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    tts = gTTS(text=script_text, lang=lang, slow=slow)
    tts.save(str(output_path))

    return output_path


if __name__ == "__main__":
    # Simple test: create a small sample audio file
    demo_text = "This is a test voiceover generated by g T T S for my YouTube automation project."
    out = Path("data/processed/audio/demo_voiceover.mp3")
    generate_voiceover(demo_text, out)
    print(f"Saved demo voiceover to: {out}")
